export const twelveHourForecast = [
  {
    DateTime: '2023-08-19T17:00:00+01:00',
    EpochDateTime: 1692460800,
    WeatherIcon: 3,
    IconPhrase: 'Partly sunny',
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 23.9,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=17&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=17&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T18:00:00+01:00',
    EpochDateTime: 1692464400,
    WeatherIcon: 3,
    IconPhrase: 'Partly sunny',
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 23.3,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=18&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=18&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T19:00:00+01:00',
    EpochDateTime: 1692468000,
    WeatherIcon: 3,
    IconPhrase: 'Partly sunny',
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 22.8,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=19&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=19&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T20:00:00+01:00',
    EpochDateTime: 1692471600,
    WeatherIcon: 2,
    IconPhrase: 'Mostly sunny',
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 22.2,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=20&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=20&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T21:00:00+01:00',
    EpochDateTime: 1692475200,
    WeatherIcon: 34,
    IconPhrase: 'Mostly clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 20.6,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=21&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=21&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T22:00:00+01:00',
    EpochDateTime: 1692478800,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 20,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=22&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=22&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-19T23:00:00+01:00',
    EpochDateTime: 1692482400,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 18.9,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=23&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=1&hbhhour=23&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-20T00:00:00+01:00',
    EpochDateTime: 1692486000,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 18.3,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=0&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=0&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-20T01:00:00+01:00',
    EpochDateTime: 1692489600,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 17.6,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=1&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=1&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-20T02:00:00+01:00',
    EpochDateTime: 1692493200,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 17,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=2&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=2&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-20T03:00:00+01:00',
    EpochDateTime: 1692496800,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 16.6,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=3&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=3&unit=c&lang=en-us',
  },
  {
    DateTime: '2023-08-20T04:00:00+01:00',
    EpochDateTime: 1692500400,
    WeatherIcon: 33,
    IconPhrase: 'Clear',
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 16.1,
      Unit: 'C',
      UnitType: 17,
    },
    PrecipitationProbability: 0,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=4&unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/hourly-weather-forecast/328328?day=2&hbhhour=4&unit=c&lang=en-us',
  },
];

export const dailyForecast = {
  Headline: {
    EffectiveDate: '2023-08-20T08:00:00+01:00',
    EffectiveEpochDate: 1692514800,
    Severity: 4,
    Text: 'Pleasant Sunday',
    Category: 'mild',
    EndDate: null,
    EndEpochDate: null,
    MobileLink:
      'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?unit=c&lang=en-us',
  },
  DailyForecasts: [
    {
      Date: '2023-08-18T07:00:00+01:00',
      EpochDate: 1692338400,
      Sun: {
        Rise: '2023-08-18T05:50:00+01:00',
        EpochRise: 1692334200,
        Set: '2023-08-18T20:18:00+01:00',
        EpochSet: 1692386280,
      },
      Moon: {
        Rise: '2023-08-18T07:43:00+01:00',
        EpochRise: 1692340980,
        Set: '2023-08-18T21:17:00+01:00',
        EpochSet: 1692389820,
        Phase: 'WaxingCrescent',
        Age: 2,
      },
      Temperature: {
        Minimum: {
          Value: 18.9,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 23.9,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 17.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 23.3,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 17.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 22.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      HoursOfSun: 1.3,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 3,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 3,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 15,
        IconPhrase: 'Thunderstorms',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Light',
        ShortPhrase: 'A shower and thunderstorm',
        LongPhrase: 'Mostly cloudy with a couple of showers and a thunderstorm',
        PrecipitationProbability: 97,
        ThunderstormProbability: 39,
        RainProbability: 97,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 16.1,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 101,
            Localized: 'E',
            English: 'E',
          },
        },
        WindGust: {
          Speed: {
            Value: 35.4,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 101,
            Localized: 'E',
            English: 'E',
          },
        },
        TotalLiquid: {
          Value: 9.7,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 9.7,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 6.5,
        HoursOfRain: 6.5,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 95,
        Evapotranspiration: {
          Value: 1.8,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 3639.2,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 12,
        IconPhrase: 'Showers',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Moderate',
        ShortPhrase: 'A few evening showers',
        LongPhrase:
          'A couple of showers this evening; otherwise, mainly cloudy, warm and humid',
        PrecipitationProbability: 86,
        ThunderstormProbability: 19,
        RainProbability: 86,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 12.9,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 176,
            Localized: 'S',
            English: 'S',
          },
        },
        WindGust: {
          Speed: {
            Value: 33.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 176,
            Localized: 'S',
            English: 'S',
          },
        },
        TotalLiquid: {
          Value: 4.6,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 4.6,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 2,
        HoursOfRain: 2,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 87,
        Evapotranspiration: {
          Value: 0.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 269.9,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&unit=c&lang=en-us',
    },
    {
      Date: '2023-08-19T07:00:00+01:00',
      EpochDate: 1692424800,
      Sun: {
        Rise: '2023-08-19T05:52:00+01:00',
        EpochRise: 1692420720,
        Set: '2023-08-19T20:16:00+01:00',
        EpochSet: 1692472560,
      },
      Moon: {
        Rise: '2023-08-19T08:53:00+01:00',
        EpochRise: 1692431580,
        Set: '2023-08-19T21:27:00+01:00',
        EpochSet: 1692476820,
        Phase: 'WaxingCrescent',
        Age: 3,
      },
      Temperature: {
        Minimum: {
          Value: 14.4,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 24.7,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 13.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 25,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 13.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 22.6,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      HoursOfSun: 7.3,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 2,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 1,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 300,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 5,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 4,
        IconPhrase: 'Intermittent clouds',
        HasPrecipitation: false,
        ShortPhrase: 'Warm with sun and clouds',
        LongPhrase: 'Warm with times of sun and clouds',
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 20.4,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 225,
            Localized: 'SW',
            English: 'SW',
          },
        },
        WindGust: {
          Speed: {
            Value: 44.4,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 222,
            Localized: 'SW',
            English: 'SW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 51,
        Evapotranspiration: {
          Value: 3.6,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 6250.6,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: 'Partly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Partly cloudy',
        LongPhrase: 'Partly cloudy',
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 11.1,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 226,
            Localized: 'SW',
            English: 'SW',
          },
        },
        WindGust: {
          Speed: {
            Value: 33.3,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 219,
            Localized: 'SW',
            English: 'SW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 32,
        Evapotranspiration: {
          Value: 0.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 190,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&unit=c&lang=en-us',
    },
    {
      Date: '2023-08-20T07:00:00+01:00',
      EpochDate: 1692511200,
      Sun: {
        Rise: '2023-08-20T05:53:00+01:00',
        EpochRise: 1692507180,
        Set: '2023-08-20T20:14:00+01:00',
        EpochSet: 1692558840,
      },
      Moon: {
        Rise: '2023-08-20T10:03:00+01:00',
        EpochRise: 1692522180,
        Set: '2023-08-20T21:37:00+01:00',
        EpochSet: 1692563820,
        Phase: 'WaxingCrescent',
        Age: 4,
      },
      Temperature: {
        Minimum: {
          Value: 14.5,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 25,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 13.7,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 25.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 13.7,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 23.3,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      HoursOfSun: 4.7,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 2,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 1,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 330,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 7,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 13,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 3,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 3,
        IconPhrase: 'Partly sunny',
        HasPrecipitation: false,
        ShortPhrase: 'Nice and warm with some sun',
        LongPhrase: 'Nice and warm with partial sunshine',
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 14.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 232,
            Localized: 'SW',
            English: 'SW',
          },
        },
        WindGust: {
          Speed: {
            Value: 31.5,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 229,
            Localized: 'SW',
            English: 'SW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 63,
        Evapotranspiration: {
          Value: 3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 4572.3,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 38,
        IconPhrase: 'Mostly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Mostly cloudy',
        LongPhrase: 'Mostly cloudy',
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 11.1,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 235,
            Localized: 'SW',
            English: 'SW',
          },
        },
        WindGust: {
          Speed: {
            Value: 22.2,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 231,
            Localized: 'SW',
            English: 'SW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 40,
        Evapotranspiration: {
          Value: 0.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 17.7,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&unit=c&lang=en-us',
    },
    {
      Date: '2023-08-21T07:00:00+01:00',
      EpochDate: 1692597600,
      Sun: {
        Rise: '2023-08-21T05:55:00+01:00',
        EpochRise: 1692593700,
        Set: '2023-08-21T20:12:00+01:00',
        EpochSet: 1692645120,
      },
      Moon: {
        Rise: '2023-08-21T11:15:00+01:00',
        EpochRise: 1692612900,
        Set: '2023-08-21T21:49:00+01:00',
        EpochSet: 1692650940,
        Phase: 'WaxingCrescent',
        Age: 5,
      },
      Temperature: {
        Minimum: {
          Value: 15.2,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 25.5,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 14.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 25.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 14.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 23.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      HoursOfSun: 5.5,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 2,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 2,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 363,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 20,
          Category: 'Moderate',
          CategoryValue: 2,
        },
        {
          Name: 'Tree',
          Value: 35,
          Category: 'Moderate',
          CategoryValue: 2,
        },
        {
          Name: 'UVIndex',
          Value: 5,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 4,
        IconPhrase: 'Intermittent clouds',
        HasPrecipitation: false,
        ShortPhrase: 'Warm with periods of sun',
        LongPhrase: 'Warm with periods of clouds and sunshine',
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 13,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 248,
            Localized: 'WSW',
            English: 'WSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 29.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 254,
            Localized: 'WSW',
            English: 'WSW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 65,
        Evapotranspiration: {
          Value: 3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 5604.2,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: 'Partly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Partly cloudy',
        LongPhrase: 'Partly cloudy',
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 268,
            Localized: 'W',
            English: 'W',
          },
        },
        WindGust: {
          Speed: {
            Value: 20.4,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 270,
            Localized: 'W',
            English: 'W',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 40,
        Evapotranspiration: {
          Value: 0.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 162.7,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&unit=c&lang=en-us',
    },
    {
      Date: '2023-08-22T07:00:00+01:00',
      EpochDate: 1692684000,
      Sun: {
        Rise: '2023-08-22T05:56:00+01:00',
        EpochRise: 1692680160,
        Set: '2023-08-22T20:09:00+01:00',
        EpochSet: 1692731340,
      },
      Moon: {
        Rise: '2023-08-22T12:29:00+01:00',
        EpochRise: 1692703740,
        Set: '2023-08-22T22:02:00+01:00',
        EpochSet: 1692738120,
        Phase: 'WaxingCrescent',
        Age: 6,
      },
      Temperature: {
        Minimum: {
          Value: 15.1,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 25.9,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 13.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 26.5,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 13.8,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Cool',
        },
        Maximum: {
          Value: 24.3,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
      },
      HoursOfSun: 8.5,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 2,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 2,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 490,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 26,
          Category: 'Moderate',
          CategoryValue: 2,
        },
        {
          Name: 'Tree',
          Value: 46,
          Category: 'Moderate',
          CategoryValue: 2,
        },
        {
          Name: 'UVIndex',
          Value: 5,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 3,
        IconPhrase: 'Partly sunny',
        HasPrecipitation: false,
        ShortPhrase: 'Partly sunny, nice and warm',
        LongPhrase: 'Nice and warm with partial sunshine',
        PrecipitationProbability: 5,
        ThunderstormProbability: 0,
        RainProbability: 5,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 13,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 278,
            Localized: 'W',
            English: 'W',
          },
        },
        WindGust: {
          Speed: {
            Value: 22.2,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 279,
            Localized: 'W',
            English: 'W',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 47,
        Evapotranspiration: {
          Value: 3.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 6185.6,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 34,
        IconPhrase: 'Mostly clear',
        HasPrecipitation: false,
        ShortPhrase: 'Clear to partly cloudy',
        LongPhrase: 'Clear to partly cloudy',
        PrecipitationProbability: 9,
        ThunderstormProbability: 0,
        RainProbability: 9,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 11.1,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 283,
            Localized: 'WNW',
            English: 'WNW',
          },
        },
        WindGust: {
          Speed: {
            Value: 14.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 305,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 17,
        Evapotranspiration: {
          Value: 0.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 165.2,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&unit=c&lang=en-us',
    },
  ],
};
export const autocomplete = [
  {
    Version: 1,
    Key: '51097',
    Type: 'City',
    Rank: 20,
    LocalizedName: 'Sofia',
    Country: {
      ID: 'BG',
      LocalizedName: 'Bulgaria',
    },
    AdministrativeArea: {
      ID: '22',
      LocalizedName: 'Sofia City',
    },
  },
  {
    Version: 1,
    Key: '60807',
    Type: 'City',
    Rank: 23,
    LocalizedName: 'Songjiang District',
    Country: {
      ID: 'CN',
      LocalizedName: 'China',
    },
    AdministrativeArea: {
      ID: 'SH',
      LocalizedName: 'Shanghai',
    },
  },
  {
    Version: 1,
    Key: '2333004',
    Type: 'City',
    Rank: 25,
    LocalizedName: 'Songyuan',
    Country: {
      ID: 'CN',
      LocalizedName: 'China',
    },
    AdministrativeArea: {
      ID: 'JL',
      LocalizedName: 'Jilin',
    },
  },
  {
    Version: 1,
    Key: '204849',
    Type: 'City',
    Rank: 25,
    LocalizedName: 'Solapur',
    Country: {
      ID: 'IN',
      LocalizedName: 'India',
    },
    AdministrativeArea: {
      ID: 'MH',
      LocalizedName: 'Maharashtra',
    },
  },
  {
    Version: 1,
    Key: '255421',
    Type: 'City',
    Rank: 31,
    LocalizedName: 'Sokoto',
    Country: {
      ID: 'NG',
      LocalizedName: 'Nigeria',
    },
    AdministrativeArea: {
      ID: 'SO',
      LocalizedName: 'Sokoto',
    },
  },
  {
    Version: 1,
    Key: '2330444',
    Type: 'City',
    Rank: 32,
    LocalizedName: 'Songpa-gu',
    Country: {
      ID: 'KR',
      LocalizedName: 'South Korea',
    },
    AdministrativeArea: {
      ID: '11',
      LocalizedName: 'Seoul',
    },
  },
  {
    Version: 1,
    Key: '298079',
    Type: 'City',
    Rank: 32,
    LocalizedName: 'Soshanguve',
    Country: {
      ID: 'ZA',
      LocalizedName: 'South Africa',
    },
    AdministrativeArea: {
      ID: 'GP',
      LocalizedName: 'Gauteng',
    },
  },
  {
    Version: 1,
    Key: '59318',
    Type: 'City',
    Rank: 33,
    LocalizedName: 'Songzi',
    Country: {
      ID: 'CN',
      LocalizedName: 'China',
    },
    AdministrativeArea: {
      ID: 'HB',
      LocalizedName: 'Hubei',
    },
  },
  {
    Version: 1,
    Key: '108205',
    Type: 'City',
    Rank: 35,
    LocalizedName: 'Soacha',
    Country: {
      ID: 'CO',
      LocalizedName: 'Colombia',
    },
    AdministrativeArea: {
      ID: 'CUN',
      LocalizedName: 'Cundinamarca',
    },
  },
  {
    Version: 1,
    Key: '3558165',
    Type: 'City',
    Rank: 35,
    LocalizedName: 'Soc Son',
    Country: {
      ID: 'VN',
      LocalizedName: 'Vietnam',
    },
    AdministrativeArea: {
      ID: 'HN',
      LocalizedName: 'Hanoi',
    },
  },
];
